/* © 2016 Zaption, Inc. All rights reserved. Modification of this file, or reuse of its contents outside of its original context, is forbidden. */
/*

 eventsource.js
 Available under MIT License (MIT)
 https://github.com/Yaffle/EventSource/
*/
(function(b){function g(){this.data={}}function a(){this.listeners=new g}function d(a){setTimeout(function(){throw a;},0)}function e(a){this.type=a;this.target=null}function k(a,b){e.call(this,a);this.data=b.data;this.lastEventId=b.lastEventId}function f(a,b){var c=Number(a)||b;return c<R?R:c>M?M:c}function c(a,b,c){try{"function"===typeof b&&b.call(a,c)}catch(h){d(h)}}function l(a,h){function l(a){var b=s===D||s===z?m.responseText||"":"",h=null,d=!1;if(s===z){var h=0,g="",v="";if(F)try{h=Number(m.status||
0),g=String(m.statusText||""),v=String(m.getResponseHeader("Content-Type")||"")}catch(n){h=0}else h=200,v=m.contentType;if(200===h&&X.test(v)){if(s=D,G=!0,x=E,t.readyState=D,h=new e("open"),t.dispatchEvent(h),c(t,t.onopen,h),s===H)return}else if(0!==h){var q="",q=200!==h?"EventSource's response has a status "+h+" "+g.replace(/\s+/g," ")+" that is not 200. Aborting the connection.":"EventSource's response has a Content-Type specifying an unsupported type: "+v.replace(/\s+/g," ")+". Aborting the connection.";
setTimeout(function(){throw Error(q);});d=!0}}if(s===D){b.length>I&&(G=!0);for(var g=I-1,v=b.length,w="\n";++g<v;)if(w=b[g],r===O&&"\n"===w)r=A;else if(r===O&&(r=A),"\r"===w||"\n"===w){"data"===y?J.push(u):"id"===y?N=u:"event"===y?B=u:"retry"===y?x=E=f(u,E):"heartbeatTimeout"===y&&(K=f(u,K),0!==p&&(clearTimeout(p),p=setTimeout(C,K)));y=u="";if(r===A){if(0!==J.length&&(P=N,""===B&&(B="message"),h=new k(B,{data:J.join("\n"),lastEventId:N}),t.dispatchEvent(h),"message"===B&&c(t,t.onmessage,h),s===H))return;
J.length=0;B=""}r="\r"===w?O:A}else r===A&&(r=S),r===S?":"===w?r=T:y+=w:r===T?(" "!==w&&(u+=w),r=U):r===U&&(u+=w);I=v}s!==D&&s!==z||!(a||d||1048576<I||0===p&&!G)?0===p&&(G=!1,p=setTimeout(C,K)):(s=Q,m.abort(),0!==p&&(clearTimeout(p),p=0),x>16*E&&(x=16*E),x>M&&(x=M),p=setTimeout(C,x),x=2*x+1,t.readyState=z,h=new e("error"),t.dispatchEvent(h),c(t,t.onerror,h))}function d(){l(!1)}function n(){l(!0)}a=String(a);var q=Boolean(v&&h&&h.withCredentials),E=f(h?h.retry:NaN,1E3),K=f(h?h.heartbeatTimeout:NaN,
45E3),P=h&&h.lastEventId&&String(h.lastEventId)||"",t=this,x=E,G=!1,m=new V,p=0,L=0,I=0,s=Q,J=[],N="",B="",C=null,r=A,y="",u="";h=null;F&&(L=setTimeout(function W(){3===m.readyState&&d();L=setTimeout(W,500)},0));C=function(){p=0;if(s!==Q)l(!1);else if(F&&(void 0!==m.sendAsBinary||void 0===m.onloadend)&&b.document&&b.document.readyState&&"complete"!==b.document.readyState)p=setTimeout(C,4);else{m.onload=m.onerror=n;F&&(m.onabort=n,m.onreadystatechange=d);m.onprogress=d;G=!1;p=setTimeout(C,K);I=0;s=
z;J.length=0;B="";N=P;y=u="";r=A;var c=a.slice(0,5),c="data:"!==c&&"blob:"!==c?a+((-1===a.indexOf("?",0)?"?":"&")+"lastEventId="+encodeURIComponent(P)+"&r="+String(Math.random()+1).slice(2)):a;m.open("GET",c,!0);F&&(m.withCredentials=q,m.responseType="text",m.setRequestHeader("Accept","text/event-stream"));m.send(null)}};this.listeners=new g;this.close=function(){s=H;null!==m&&(m.abort(),m=null);0!==p&&(clearTimeout(p),p=0);0!==L&&(clearTimeout(L),L=0);t.readyState=H};this.url=a;this.readyState=z;
this.withCredentials=q;this.onerror=this.onmessage=this.onopen=null;C()}function h(){this.CONNECTING=z;this.OPEN=D;this.CLOSED=H}g.prototype={get:function(a){return this.data[a+"~"]},set:function(a,b){this.data[a+"~"]=b},"delete":function(a){delete this.data[a+"~"]}};a.prototype={dispatchEvent:function(a){a.target=this;var b=this.listeners.get(String(a.type));if(b)for(var c=b.length,h=-1,l=null;++h<c;){l=b[h];try{l.call(this,a)}catch(f){d(f)}}},addEventListener:function(a,b){a=String(a);var c=this.listeners,
h=c.get(a);h||(h=[],c.set(a,h));for(c=h.length;0<=--c;)if(h[c]===b)return;h.push(b)},removeEventListener:function(a,b){a=String(a);var c=this.listeners,h=c.get(a);if(h){for(var l=h.length,f=[],d=-1;++d<l;)h[d]!==b&&f.push(h[d]);if(0===f.length)c["delete"](a);else c.set(a,f)}}};k.prototype=e.prototype;var q=b.XMLHttpRequest,n=b.XDomainRequest,v=Boolean(q&&void 0!==(new q).withCredentials),F=v,V=v?q:n,Q=-1,z=0,D=1,H=2,O=3,A=4,S=5,T=6,U=7,X=/^text\/event\-stream;?(\s*charset\=utf\-8)?$/i,R=1E3,M=18E6;
h.prototype=a.prototype;l.prototype=new h;h.call(l);V&&(b.NativeEventSource=b.EventSource,b.EventSource=l)})(this);
(function(){ZAP.TourHistorian=function(b,g){var a=this,d=[],e=0,k=[],f=0,c=Date.now(),l=0.08,h,q=function(){h=Date.now();var a=setInterval(function(){var b=Date.now()-h,c=0.92*((b=b/6E5-1)*b*b+1)+0.08;l=Math.min(c,1);1===l&&(clearInterval(a),a=null)},1E3)},n=null;a.startTimeTracker=function(){n||(n=Date.now(),h||q())};a.stopTimeTracker=function(){n&&(e+=Date.now()-n,n=null,a.considerSendingHistoryData.debounced())};a.consolidateTimeTracker=function(){n&&(e+=Date.now()-n,n=Date.now(),a.considerSendingHistoryData.debounced())};
a.trackEvent=function(b,c){d.push({name:b,data:c});a.considerSendingHistoryData.debounced()};a.trackFinished=function(b){a.trackEvent("tourFinished",b);a.sendHistoryData()};a.sendHistoryData=function(){if((d.length||e)&&!k.length&&!f){a.consolidateTimeTracker();k=d;f=e;e=0;d=[];var h={tourId:b,extraTime:f/1E3,events:k,viewerName:g(),ltiSessionId:window.ltiSessionId,fingerprint:window.fingerprint};ZAP.player.standalone&&ZAP.player.webhookUrl&&(h.type="progress");ZAP.player.standalone&&!ZAP.player.webhookUrl||
amplify.request({resourceId:"sendTourHistoryData",data:h,success:function(){k=[];f=0;c=Date.now()},error:function(a){log("TourHistorian: Error: "+(a?a.message:"Unknown error"));d=k.concat(d);e+=f;k=[];f=0;a.refresh&&(window.zp&&window.zp.pause(),window.trackJs&&window.trackJs.track(Error("CSRF failure forcing refresh on /progress.")),ZAP.showAlert("You have been logged out or something went wrong with your session. You'll need to refresh the page to continue.",{afterClose:function(){window.location.reload()}}))}})}};
a.considerSendingHistoryData=function(){d.length>6*l?a.sendHistoryData():e>5E4*l?a.sendHistoryData():Date.now()-c>4E4*l&&a.sendHistoryData()};a.considerSendingHistoryData.debounced=_.debounce(a.considerSendingHistoryData,1E3);setInterval(function(){a.consolidateTimeTracker();a.considerSendingHistoryData()},2E4)};ZAP.TourHistorian.defineRequest=function(){var b="/ajax/history/tours/{tourId}/progress";ZAP.player&&ZAP.player.standalone&&ZAP.player.webhookUrl&&(b=ZAP.player.webhookUrl);amplify.request.define("sendTourHistoryData",
"ajax",{url:b,dataType:"json",contentType:"application/json",type:"POST",decoder:"zsend"})};ZAP.TourHistorian.defineRequest()})();
ZAP.defineViewTourViewModels=function(){function b(a){return _.reduce(a,function(a,b){return _.contains(f,b.elementType())?a.concat([b]):"Group"===b.elementType()?a.concat(g(b.children())):a},[])}function g(a){return _.reduce(a,function(a,b){return _.contains(c,b.elementType())?a.concat([b]):"Group"===b.elementType()?a.concat(g(b.children())):a},[])}function a(b){return _.reduce(b,function(b,c){return c.canGrade()?b+1:"Group"===c.elementType()?b+a(c.children()):b},0)}function d(a){return _.reduce(a,
function(a,b){return b.canGrade()&&b.isCorrect()?a+b.points():"Group"===b.elementType()?a+d(b.children()):a},0)}function e(a){return _.reduce(a,function(a,b){return b.canGrade()&&b.isCorrect()?a+1:"Group"===b.elementType()?a+e(b.children()):a},0)}function k(a){return _.reduce(a,function(a,b){return b.response()&&b.response()!==fabric.Canvas.EMPTY_JSON||0===b.response()||b.responses().length?a+1:"Group"===b.elementType()?a+k(b.children()):a},0)}var f="Discussion TextResponse NumResponse DrawnResponse MultipleChoice CheckBoxes".split(" "),
c=_.without(f,"Discussion"),l=["TextResponse","NumResponse","DrawnResponse","MultipleChoice","CheckBoxes"];ZAP.TourElement.loadExtensions("canGrade","isCorrect","responseHtml","tooltipClassName","visibleMarker");ZAP.Tour.loadExtensions("activeClip","totalPoints");window.ViewTourModel=function(){var c=this;c.tour=ko.observable(new ZAP.Tour(window.initialTour,{preSynced:!0,temporary:!window.userOwns}));c.responseElements=ko.computed(function(){return ZAP.sort.tourElements(c.tour().clips(),b(c.tour().filteredElements()))});
c.questions=ko.computed(function(){return g(c.tour().filteredElements())});c.numberOfQuestions=ko.computed(function(){return c.questions().length});c.numberOfGradedQuestions=ko.computed(function(){return a(c.tour().filteredElements())});c.numberOfQuestionsAnswered=ko.computed(function(){return k(c.questions())});c.numberOfCorrectResponses=ko.computed(function(){return e(c.tour().filteredElements())});c.collectedPoints=ko.computed(function(){return c.tour().completionPoints()+d(c.tour().filteredElements())});
c.tour().elementsFilter(function(a){return!a.presentationId()});c.liveMainElements=ko.observable(!1);c.liveSideElements=ko.observable(!1);c.showPlaybackRate=ko.observable(!0);c.playbackRate=ko.observable(1);c.needsTouchToPlay=ko.observable(!!window.isTablet);c.showPlayHints=ko.computed(function(){return c.liveMainElements()&&c.liveSideElements()?_.any([c.liveMainElements(),c.liveSideElements()],function(a){if(!a.stoppingVideo())return!1;a=a.activeElement();return _(["TextScreen","ImageScreen","Drawing"]).contains(a.elementType())||
"Group"===a.elementType()&&a.activeChild()&&_(["TextScreen","ImageScreen","Drawing"]).contains(a.activeChild().elementType())?!0:!1}):!1});c.showPlayHintsNormal=ko.computed(function(){return c.showPlayHints()&&!c.isFullscreen()});c.showPlayHintsFullscreen=ko.computed(function(){return c.showPlayHints()&&c.isFullscreen()});c.activeClip=ko.observable(!1);c.seekWidth=ko.observable($(".seekbar").innerWidth());c.rating=ko.observable(0);c.player=ko.observable(null);c.getSidebarTitle=ko.computed(function(){if(c.liveSideElements().activeElement&&
c.liveSideElements().activeElement()){var a=c.liveSideElements().activeElement().elementType();"Group"===a&&(a=c.liveSideElements().activeElement().activeChild().elementType());return ZAP.elementMap.elementTypeToLabel(a)}return""});c.getSidebarIcon=ko.computed(function(){if(c.liveSideElements().activeElement&&c.liveSideElements().activeElement()){var a=c.liveSideElements().activeElement().elementType();"Group"===a&&(a=c.liveSideElements().activeElement().activeChild().elementType());return ZAP.elementMap.elementTypeToIcon(a)}return""});
c.isFullscreen=ko.computed(function(){return c.player()&&c.player().isFullScreenMode()});var f=function(){if(!window.currentUser){var a=function(b){"Group"===b.elementType()?b.children().forEach(a):_.contains(l,b.elementType())&&b.restoreResponseFromLocal(window.fingerprint,c.viewerName())};c.tour().filteredElements().forEach(a)}},n=function(a){var b=ZaptionPlayer("ZaptionPlayer");c.player(b);a&&b.play();b.resumeElementsQueues();$(".player-controls").focus();$(".tour-intro").fadeOut(350,function(){$(".player-controls-holder.not-fullscreen").fadeIn(350,
function(){$(".tour-intro").removeClass("active")})})};c.viewerName=ko.observable(window.initialViewerName);c.viewerNameMaxLength=50;c.viewerName.store=function(){return c.viewerName().length<=c.viewerNameMaxLength?(ZAP.setLocalUsername(c.viewerName()),f(),!0):!1};window.currentUser||(c.viewerName(ZAP.getLocalUsername(c.tour().noNameRequired())),f());c.updateTourProgress=function(){var a=zp.currentTime(),b={dateViewed:Date.now()};zp.liveMainElements.stoppingVideo()?b.element=zp.liveMainElements.activeElement()._id:
zp.liveSideElements.stoppingVideo()?b.element=zp.liveSideElements.activeElement()._id:(b.clipIndex=zp.playlist().indexOf(zp.getCurrentItem()),b.time=a);window.currentUser?b.uid=window.currentUser._id:b.viewerName=c.viewerName();amplify.store("ZPTourProgress/"+c.tour()._id,b,{expires:26784E5});c.updateTourProgress.lastUpdate=a};c.updateTourProgress.lastUpdate=0;c.hasValidProgress=function(){var a=amplify.store("ZPTourProgress/"+c.tour()._id);if(!a)return!1;var b=!a.uid&&!window.currentUser&&a.viewerName===
c.viewerName()||window.currentUser&&a.uid===window.currentUser._id,l=c.tour().dateUpdated().getTime()<=a.dateViewed,a=a.element||0!==a.clipIndex||0!==a.time;return b&&l&&a};c.restoreTourProgress=function(){var a=amplify.store("ZPTourProgress/"+c.tour()._id);c.hasValidProgress()&&(a.element?zp.goToElement(a.element):(zp.setCurrentItem(a.clipIndex),zp.seek(a.time,!0)),n(!1))};c.clearTourProgress=function(){amplify.store("ZPTourProgress/"+c.tour()._id,null)};c.cloneTour=function(){var a=$('<form method="post" action="/tours/'+
c.tour()._id+'/clone"></form>');a.append('<input type="hidden" name="_csrf" value="'+window.csrfToken+'">');$("body").append(a);a.submit()};c.unpublishTour=function(){var a=$('<form method="post" action="/tours/'+c.tour()._id+'/unpublish"></form>');a.append('<input type="hidden" name="_csrf" value="'+window.csrfToken+'">');$("body").append(a);a.submit()};c.showUnpublishWarning=function(){$("#unpublishTourWarning").reveal()};c.showDeleteTourWarning=function(){$("#deleteTourWarning").reveal()};c.deleteTour=
function(){amplify.request({resourceId:"deleteItem",data:{itemType:"tour",id:c.tour()._id},success:function(){ZAP.showAlert("This lesson has been deleted.",{afterClose:function(){window.location="/lessons"}})},error:function(a){ZAP.showAlert("Uh oh! We were unable to delete this lesson. The error was: "+a.message)}})};window.attachTourSettingsTo(c,{restrictions:restrictions});c.clickedStartTour=function(){window.zp&&ZAP.is.mobile&&ZAP.is.android&&window.zp.goFullScreenVideo();if(window.needsCookieSet())return window.postCookieSet=
function(){window.needsCookieSet()?ZAP.showAlert("Your browser has cookies disabled. You need to enable cookies in order to use Zaption."):c.clickedStartTour()},!0;!window.zp||"view"!==window.zp.playerMode||window.currentUser||c.viewerName()||c.tour().noNameRequired()?n(!0):$("#identifyViewerPrompt").reveal({closeOnBackgroundClick:!1,disableEsc:!0})};c.createPresentation=function(){ZAP.presenter.continueOrCreatePresentation(c.tour())};c.finishTour=function(){c.clearTourProgress();window.hideFeedback||
($(".tour-outro").fadeIn(350),$(".player-controls-holder.not-fullscreen").fadeOut(350,function(){$(".tour-outro").addClass("active")}))};c.replayTour=function(){var a=ZaptionPlayer("ZaptionPlayer");a.restartPlaylist();a.play();$(".tour-outro").fadeOut(350);$(".player-controls-holder.not-fullscreen").fadeIn(350,function(){$(".tour-outro").removeClass("active")})};c.goBackToElement=function(a){var b=ZaptionPlayer("ZaptionPlayer");$("#viewResponses").trigger("reveal:close");$(".tour-outro").fadeOut(350);
$(".player-controls-holder.not-fullscreen").fadeIn(350,function(){$(".tour-outro").removeClass("active")});b.goToElement(a)};c.exportWithWebhook=function(a){var b=$(a).find('[name="webhookUrl"]').val(),b="/exporter/lessons/"+c.tour()._id+"?webhook="+b;$("body").trigger("close-bubble");window.location=b;$(a).find('[name="webhookUrl"]').val("")}}};var defineMyGroupsViewModel=function(){window.MyGroupsViewModel=function(){this.myGroups=ko.observableArray(window.initialGroups)}};
ZAP.runMyGroupsPage=function(){$(document).ready(function(){defineMyGroupsViewModel();$(".application-container").show();var b=new window.MyGroupsViewModel;window.addKnockoutBindings(ko);ko.applyBindings(b)})};
var attachTourSearchTo=function(b){amplify.request.define("addTour","ajax",{url:"/ajax/tours/{tourId}/grant/readwrite",dataType:"json",type:"POST",decoder:"zsend"});b.currentPage=ko.observable(0);b.resultsPerPage=ko.observable(12);b.numPages=ko.observable(0);b.searchTerm=ko.observable("");b.findTourModalTitle=ko.observable("Add a lesson to this group");b.showReset=ko.observable(!1);b.dataLoaded=ko.observable(!1);b.items=ko.observableArray();var g=function(a){amplify.request({resourceId:"addTour",
data:{tourId:a._id,entity:{id:b.group._id,type:"group"},type:"read"},success:function(){amplify.request.invalidate(["browseTours","getGroupTours"]);b.reloadTours();k()}});$(".add-tour-modal").trigger("reveal:close")},a=function(a){b.items.removeAll();_.forEach(a,function(a){b.items.push(new ZAP.Tour(a,{preSynced:!0}))});b.dataLoaded(!0)};b.search=function(a){b.searchTerm(encodeURIComponent(a.searchText.value));0<b.currentPage()?b.currentPage(0):k()};b.resetTours=function(){b.searchTerm()&&(b.searchTerm(""),
$("input[name=searchText]").val(""));0<b.currentPage()?b.currentPage(0):k();b.showReset(!1)};b.tourClick=function(a){g(a)};b.closeTourModal=function(){$(".add-tour-modal").trigger("reveal:close")};var d=function(f){void 0!==f.totalCount&&b.numPages(f.totalCount/b.resultsPerPage());a(f.results)},e=function(a,c){"abort"!==c&&ZAP.showAlert(a.message);b.dataLoaded(!0)},k=b.refreshResults=function(){var a={sort:"dateUpdatedDesc",numItems:b.resultsPerPage(),page:b.currentPage(),itemType:"tour",groupId:window.initialGroup._id};
b.findTourModalTitle("My Lessons:");b.searchTerm()?(b.findTourModalTitle("Search Results"),a.terms=b.searchTerm(),b.showReset(!0)):b.searchTerm()||b.showReset(!1);b.dataLoaded(!1);amplify.request({resourceId:"browseTours",success:d,error:e,data:a})};b.nextPage=function(){b.numPages()-1>b.currentPage()&&b.currentPage(b.currentPage()+1)};b.prevPage=function(){0<b.currentPage()&&b.currentPage(b.currentPage()-1)};b.currentPage.subscribe(k)},defineGroupViewModel=function(){window.GroupViewModel=function(){amplify.request.define("getGroupTours",
"ajax",{url:"/ajax/groups/{gid}/tours",type:"GET",decoder:"zsend",dataType:"json",cache:6E4});amplify.request.define("removeTour","ajax",{url:"/ajax/groups/{gid}/tours/{tid}",type:"DELETE",decoder:"zsend",dataType:"json"});amplify.request.define("getGroupUsers","ajax",{url:"/ajax/groups/{gid}",type:"GET",decoder:"zsend",dataType:"json",cache:6E4});amplify.request.define("addUser","ajax",{url:"/ajax/groups/{gid}/add",type:"POST",decoder:"zsend",dataType:"json"});amplify.request.define("removeUser",
"ajax",{url:"/ajax/groups/{gid}/{uid}",type:"DELETE",decoder:"zsend",dataType:"json"});amplify.request.define("editUser","ajax",{url:"/ajax/groups/{gid}/{uid}/edit",type:"POST",decoder:"zsend",dataType:"json"});amplify.request.define("browseTours","ajax",{url:"/ajax/tours",dataType:"json",data:{typeFilter:"group"},type:"GET",decoder:"zsend",cache:6E4});var b=this;b.editingName=ko.observable(!1);b.editingDescription=ko.observable(!1);b.setUsers=function(a){b.users().length=0;a.forEach(function(a){a=
new ZAP.GroupUser(a,{sync:"none"});b.users.push(a);a.role.subscribe(f.bind(a))})};b.users=ko.observableArray();b.groupTours=ko.observableArray();b.groupAdminNames=ko.computed(function(){return _.filter(b.users(),function(a){return"admin"===a.role()}).map(function(a){return a.fullName()})});b.groupAdminNames.deferUpdates=!1;b.userMgmtSort=ko.observable("name-asc");var g=function(a,b){var f=b?1:-1;return function(b,l){return b[a]()>l[a]()?f:b[a]()<l[a]()?-f:0}},a={"name-asc":g("fullName",!0),"name-desc":g("fullName",
!1),"date-asc":g("joinDate",!0),"date-desc":g("joinDate",!1),"role-desc":g("role",!0),"role-asc":g("role",!1)};b.userMgmtList=ko.computed(function(){var c=b.userMgmtSort();return b.users().sort(a[c])});b.userMgmtList.deferUpdates=!1;b.nameSort=function(){"name-asc"===b.userMgmtSort()?b.userMgmtSort("name-desc"):b.userMgmtSort("name-asc")};b.dateSort=function(){"date-asc"===b.userMgmtSort()?b.userMgmtSort("date-desc"):b.userMgmtSort("date-asc")};b.roleSort=function(){"role-desc"===b.userMgmtSort()?
b.userMgmtSort("role-asc"):b.userMgmtSort("role-desc")};var d=function(a,b){a?($(b).hide(),$(b+"-editable").show().focus().select()):($(b).show(),$(b+"-editable").hide())};b.editName=function(){b.editingName(!b.editingName());d(b.editingName(),".group-title");0===b.group.name().length&&b.group.name("Untitled Group")};b.editDescription=function(){b.editingDescription(!b.editingDescription());d(b.editingDescription(),".group-description")};b.reloadUsers=function(a){groupId&&amplify.request({resourceId:"getGroupUsers",
data:{gid:groupId},success:function(l){b.setUsers(l);if(a)return a(l)},error:function(a,b){"abort"!==b&&ZAP.showAlert("Failed to retrieve user list: "+a.message)}})};b.reloadTours=function(){groupId&&amplify.request({resourceId:"getGroupTours",data:{gid:groupId},success:function(a){b.groupTours(a.map(function(a){return new ZAP.Tour(a,{preSynced:!0})}))},error:function(a,b){"abort"!==b&&ZAP.showAlert("Failed to retrieve lesson list: "+a.message)}})};var e,k;$("#userEmail").autocomplete({appendTo:"#addUserForm",
source:function(a,b){e=null;return ZAP.util.getAutocompleteResults(a.term,!1,function(a,c){if(a)return ZAP.showAlert(a),k&&k(!0),b();0<c.length?(e=c[0],k&&k(null,e.id)):(e=null,k&&k(!0));return b(c)})},select:function(a,b){$("#addUserId").val(b.item.id)}});b.addUser=function(a){var f=function(f,l){k=null;if(f||!l)return!1;amplify.request({resourceId:"addUser",data:{gid:groupId,userId:l,entity:{id:l,type:"user"}},success:function(){amplify.request.invalidate("getGroupUsers");b.reloadUsers()},error:function(a){ZAP.showAlert("Failed to retrieve add user: "+
a.message)}});a.reset();a.addUserId.value="";e=null;$("#userEmail").autocomplete("close");return!1},d;if(a.addUserId.value)d=a.addUserId.value;else if(e)d=e.id;else return k=f,!1;return f(null,d)};b.editUser=function(a){var f={gid:groupId},d=!1;if(a.userId)f.uid=a.userId(),f.role=a.role();else if(a.id)f.uid=a.id.value,f.role=a.role.value,d=!0,$(".reveal-modal").trigger("reveal:close");else return!1;amplify.request({resourceId:"editUser",data:f,success:function(){amplify.request.invalidate("getGroupUsers");
d&&window.location.reload()},error:function(a){b.reloadUsers();ZAP.showAlert("Failed to edit user: "+a.message)}})};b.removeUser=function(a){var f=a.id.value;amplify.request({resourceId:"removeUser",data:{gid:groupId,uid:f},success:function(){f===window.currentUser._id?window.location.reload():(amplify.request.invalidate("getGroupUsers"),b.reloadUsers())},error:function(a){b.reloadUsers();ZAP.showAlert("Failed to remove user: "+a.message)}});$(".reveal-modal").trigger("reveal:close")};b.removeTour=
function(a){amplify.request({resourceId:"removeTour",data:{gid:groupId,tid:a.id.value},success:function(){amplify.request.invalidate("getGroupTours");b.reloadTours()},error:function(a){b.reloadTours();ZAP.showAlert("Failed to remove lesson: "+a.message)}});$(".reveal-modal").trigger("reveal:close");return!1};var f=function(a){return window.currentUser._id===this.userId()?(ZAP.showConfirmation({title:"You will no longer be able to manage this group.",prompt:"Are you sure you want to make this change?",
confirmAction:b.editUser,cancelAction:b.reloadUsers,hiddenFields:[{name:"id",value:this.userId()},{name:"role",value:a}]},b),!1):b.editUser(this)};b.showRemoveUserWarning=function(a){ZAP.showConfirmation({title:"Are you sure you want to remove "+a.fullName()+" from this group?",confirmAction:b.removeUser,hiddenFields:[{name:"id",value:a.userId()}]},b);return!1};b.showRemoveTourWarning=function(a){ZAP.showConfirmation({title:"Are you sure you want to remove this lesson?",prompt:'"'+(a.name()||"Untitled Lesson")+
'" will be removed from this group.',confirmAction:b.removeTour,hiddenFields:[{name:"id",value:a._id}]},b);return!1};b.showDeleteWarning=function(){return ZAP.showConfirmation({title:"Are you sure you want to delete this group?",confirmPostURL:"/groups/"+groupId+"/delete"},b)};b.showLeaveWarning=function(){return ZAP.showConfirmation({title:"Leave this group",prompt:"Are you sure you want to cancel your membership in this group?",confirmPostURL:"/groups/"+groupId+"/leave",confirmText:"Leave"},b)};
b.showAddTourModal=function(){$(".add-tour-modal").reveal();b.refreshResults()};attachTourSearchTo(b);$.extend(ZAP.Tour.schema,{temporary:{type:Boolean,sync:"none"},detailPage:{compute:function(){return"Tour"!==this._instanceType||this.published()?"/"+this._instanceType.toLowerCase()+"s/"+this._id:"/"+this._instanceType.toLowerCase()+"s/"+this._id+"/edit"},sync:"none"},displayType:{compute:function(){return"Tour"===this._instanceType?!0===this.published()?"StandardItem":"UnpublishedItem":"Listing"===
this._instanceType?"StandardItem":"Finished"===this.encodeStatus()?"StandardItem":"Failed"===this.encodeStatus()?"FailedItem":"EncodingItem"},sync:"none"},displayClass:{compute:function(){switch(this.displayType()){case "StandardItem":return"browse-item";case "EncodingItem":return"browse-encoding";case "FailedItem":return"browse-failed";case "UnpublishedItem":return"browse-unpublished";default:return"browse-item"}},sync:"none"},hidden:{type:Boolean,sync:"none"},readableByGroup:{compute:function(){if(this.published())return!0;
var a={_id:(new ObjectId).toString(),groups:window.currentUser.groups};return ZAP.util.checkPermission(a,"read-write-item",this)},sync:"none"},readableByUser:{compute:function(){return this.published()?!0:ZAP.util.checkPermission(window.currentUser,"read-write-item",this)},sync:"none"}});window.admin&&($.extend(ZAP.Tour.schema,{groupViewerCount:{compute:function(){var a=this;return _.reduce(window.userTourViewSets,function(b,f){return b+(f.tour===a._id?1:0)},0)},sync:"none"},groupViewPercentage:{compute:function(){var a=
100*(this.groupViewerCount()/b.users().length);return Math.round(a)},sync:"none"}}),ZAP.Tour.methods.userViewed=function(a){var b=this;return _.some(window.userTourViewSets,function(f){return f.tour===b._id&&f.user===a})});ZAP.Tour.methods.clickEvent=function(){this.readableByUser()&&(window.location.href=this.detailPage())};b.reloadTours();window.initialGroup&&(b.group=new ZAP.Group(window.initialGroup,{preSynced:!0}),b.group.name.subscribe(function(a){$("#groupName"+groupId).text(a)}));window.admin?
(g=new Clipboard("#invite-link-copy",{text:function(){return"http://zapt.io/g"+window.initialGroup.accessKey}}),g.on("success",function(a){ZAP.ui.appendMessage("Copied to Clipboard!",".invite-code-section .section-box","success",3E3);a.clearSelection()}),g.on("error",function(){ZAP.ui.appendMessage("Press Command + C to copy",".invite-code-section .section-box",3E3)}),b.reloadUsers(function(){ko.processAllDeferredBindingUpdates();$("a[href=#groupMgmt], #groupMgmtTab").toggleClass("active");$("a[href=#groupTours], #groupToursTab").toggleClass("active")})):
b.group&&b.users(b.group.users())}};ZAP.runGroupPage=function(){$(document).ready(function(){defineGroupViewModel();$(".group-title-editable").hide();$(".group-description-editable").hide();$(".application-container").show();var b=new window.GroupViewModel;window.addKnockoutBindings(ko);ko.applyBindings(b)})};
ZAP.runGroupSignupPage=function(){$(document).ready(function(){window.defineSignupViewModel();var b=new window.SignupViewModel;window.addKnockoutBindings(ko);b.group=new ZAP.Group(window.initialGroup,{preSynced:!0});b.groupAdminNames=ko.computed(function(){return _.filter(b.group.users(),function(b){return"admin"===b.role()}).map(function(b){return b.fullName()})});ko.applyBindings(b);$("#authenticate").reveal({closeOnBackgroundClick:!1,disableEsc:!0,opened:function(){var b=$(window).height(),a=$("#authenticate").outerHeight();
a<b&&$("#authenticate").css("top",(b-a)/2+"px")}});window.authComplete=function(g,a){g&&b.showModalError(g);a&&(window.location=a)};window!==top&&$(".service-btn").attr("target","_blank")})};var viewTourModel,zp;ko.bindingHandlers.clip={update:function(b,g,a,d,e){g=ko.utils.unwrapObservable(g());e=e.$root.tour();e=Math.floor(1E3*(g.duration()/e.totalDuration()))/10;$(b).css("width",e+"%")}};
ko.bindingHandlers.tourElement={update:function(b,g,a,d,e){var k=ko.utils.unwrapObservable(g()),f=e.$parent;g=e.$root;var c=ko.utils.unwrapObservable(k.inTime)+f.tourOffset;g=c/g.tour().totalDuration();$(b).css("left",100*g+"%");$(b).on("mousedown",function(a){a.stopPropagation()});$(b).on("click",function(a){if(!(zp.navigationDisabled||zp.navigationDisabledForward&&c>zp.furthestTimeViewed())){var b=zp.isPaused()||k.stopVideo()&&!k.removeAfter();zp.setCurrentItem(f,!b);zp.goToElement(k);a.stopPropagation()}})}};
var forwardEscapesToParent=function(){window!==parent&&window.addEventListener("keydown",function(b){if(27===b.keyCode){var g=new window.Event("keydown",b);g.keyCode=b.keyCode;parent.dispatchEvent(g)}})};
ZAP.runViewTourPage=function(){var b=!!_.find(window.initialTour.clips,function(b){return"YouTube"===b.videoType});ZAP.defineViewTourViewModels();ZAP.Tour.loadExtensions("callToActionLink","hasInteractiveElements");window.showSignupModal=function(){var b=ko.contextFor($("#authenticate")[0].firstChild);if(!(window.SignupViewModel&&b&&b.$root instanceof window.SignupViewModel)){window.defineSignupViewModel();var a=new window.SignupViewModel;a.tour=new ZAP.Tour(window.initialTour,{preSynced:!0});ko.applyBindingsToDescendants(a,
$("#authenticate")[0])}var d=function(){$(".reveal-modal").off("reveal:closed",d);$("#authenticate").reveal({opened:function(){var a=$(window).height(),b=$("#authenticate").outerHeight();b<a&&$("#authenticate").css("top",(a-b)/2+"px")}})};if($(".reveal-modal.open").length)$(".reveal-modal").trigger("reveal:close").on("reveal:closed",d);else d();window.authComplete=function(b,d){b&&a.showModalError(b);d&&(window.location=d)};window!==top&&$(".service-btn").attr("target","_blank")};$(document).ready(function(){var g=
"/ajax/history/tours/{tourId}/started";ZAP.player&&ZAP.player.standalone&&ZAP.player.webhookUrl&&(g=ZAP.player.webhookUrl);amplify.request.define("tourStarted","ajax",{url:g,dataType:"json",type:"POST"});amplify.request.define("rate","ajax",{url:"/ajax/history/tours/{tourId}/rate",dataType:"json",type:"POST",decoder:"zsend"});ZAP.defineAmplifyRequests(["deleteItem"]);window.addKnockoutBindings(ko);viewTourModel=new window.ViewTourModel;ko.applyBindings(viewTourModel);(new window.ShareTourViewModel(viewTourModel.tour)).bind();
$(".player-controls-holder:not(.full-screen)").hide();viewTourModel.zp=zp=ZaptionPlayer("ZaptionPlayer");viewTourModel.playheadMouseoverText=ko.computed(function(){return ZAP.util.secondsToTimestamp(zp.currentTimeOnTour())+" / "+ZAP.util.secondsToTimestamp(viewTourModel.tour().totalDuration())});$(".play-head").attr("data-bind","tooltip: { type: 'tiny', text: playheadMouseoverText, repositionOnChange: zp.currentTimeOnTour }, style: { left: (Math.floor(10000 * zp.ratioPlayed()) / 100.0) + '%' }");
ko.cleanNode($(".play-head-holder")[0]);ko.cleanNode($(".play-head-holder")[1]);ko.applyBindings(viewTourModel,$(".play-head-holder").get(0));ko.applyBindings(viewTourModel,$(".play-head-holder").get(1));viewTourModel.liveMainElements(zp.liveMainElements);viewTourModel.liveSideElements(zp.liveSideElements);zp.isPlayerMode("preview")||(viewTourModel.rating.subscribe(function(a){amplify.request({resourceId:"rate",data:{tourId:viewTourModel.tour()._id,rating:a,viewerName:viewTourModel.viewerName()}})}),
zp.on("play",function l(){if(!ZAP.player.standalone||ZAP.player.webhookUrl){var a={tourId:viewTourModel.tour()._id,viewerName:viewTourModel.viewerName()};ZAP.player.standalone&&ZAP.player.webhookUrl&&(a.type="tourStarted");amplify.request({resourceId:"tourStarted",data:a});ZAP.util.track("Started Tour",{viewerName:viewTourModel.viewerName(),tourId:viewTourModel.tour()._id,parentTour:viewTourModel.tour().parentTour(),zaptionCreated:ZAP.util.isZaptionAccount(viewTourModel.tour().owner())});zp.off("play",
l)}}));viewTourModel.showPlaybackRate(zp.hasPlaybackButtons);viewTourModel.playbackRate(zp.playbackRate);zp.liveMainElements.activeElement.subscribe(viewTourModel.updateTourProgress.bind(viewTourModel));zp.liveSideElements.activeElement.subscribe(viewTourModel.updateTourProgress.bind(viewTourModel));zp.on("timeupdate",function(){1<zp.currentTime()&&1.5<Math.abs(zp.currentTime()-viewTourModel.updateTourProgress.lastUpdate)&&viewTourModel.updateTourProgress()});zp.on("ended",function(){viewTourModel.finishTour()});
viewTourModel.tour().preventNavigationForward()&&zp.toggleNavigationForward(!1);viewTourModel.tour().preventNavigationForward.subscribe(function(a){zp.toggleNavigationForward(!a)});viewTourModel.tour().preventNavigation()&&zp.toggleNavigation(!1);viewTourModel.tour().preventNavigation.subscribe(function(a){zp.toggleNavigation(!a)});viewTourModel.tour().lockPlaybackRate()&&zp.toggleLockPlaybackRate(!0);viewTourModel.tour().lockPlaybackRate.subscribe(function(a){zp.toggleLockPlaybackRate(a)});zp.on("switchedplaylistitem",
function(){for(var a=zp.getCurrentItem()._id,b,f=viewTourModel.tour().clips(),d=0;d<f.length;d++)if(f[d]._id===a){b=f[d];break}b.transcript()&&!b.transcriptObject()&&b.loadTranscript();viewTourModel.activeClip(b)});0<viewTourModel.tour().clips().length&&viewTourModel.activeClip(viewTourModel.tour().clips()[0]);var a=function(a,b){if("zaptionHack"===b.prop){var f=a+1;$(this).css("transform","scale("+f+")")}},d=window.currentUser;!d||viewTourModel.tour().owner()!==d._id||d.promosViewed&&d.promosViewed.sharingIntro||
window.needsWelcome||ZAP.ui.pageIsFramed()||$("#refer").length||window.isiPhone||(g=$("#shareTourModal"),g.reveal(),g.on("reveal:closed",function(){ZAP.util.updatePromosViewed("sharingIntro");ZAP.util.track("Onboarding: Sharing intro completed")}));var e=$(".player-shell");$(".large-player").on("click",function(){e.hasClass("zoomed")?e.animate({zaptionHack:"0",height:"572px",marginTop:"40px"},{step:a,duration:"slow",complete:function(){e.removeAttr("style");e.removeClass("zoomed")}}):e.animate({zaptionHack:".3",
height:"625px",marginTop:"120px"},{step:a,duration:"slow",complete:function(){e.removeAttr("style");e.addClass("zoomed")}}).css("overflow","visible")});window.autoplay&&!viewTourModel.hasValidProgress()&&viewTourModel.clickedStartTour();if(window.isiPad&&_.find(viewTourModel.tour().clips(),function(a){return"S3"===a.videoType()})){var k=document.documentElement.clientHeight;setInterval(function(){if(window.innerHeight!==k){var a=0.10607866507*window.innerHeight;$(".html5-ipad-play").css({height:a+
"px",width:a+"px"});$(".html5-ipad-play").position({my:"center",at:"center",of:".video-player"});k=window.innerHeight}},0.25)}$(".application-container").show();if("#startSignup"===window.location.hash&&!d)window.location.hash="",window.showSignupModal();else if(!d&&!viewTourModel.viewerName()&&!viewTourModel.tour().noNameRequired())$("#identifyViewerPrompt").reveal({closeOnBackgroundClick:!1,disableEsc:!0});else if(!zp.isPlayerMode("preview")&&viewTourModel.hasValidProgress()&&(viewTourModel.viewerName()||
!viewTourModel.tour().noNameRequired())){var g=moment(amplify.store("ZPTourProgress/"+viewTourModel.tour()._id).dateViewed).fromNow(),f="Not <var>"+_.escape(viewTourModel.viewerName())+"</var>?",f=d?f+(' <a href="/logout?returnTo='+encodeURIComponent(window.location)+'">Click here to sign out.</a>'):f+' <a class="fake-link" data-bind="click: changeName">Click here to change your name.</a>';ZAP.player.standalone&&(f="");window.autoplay?(viewTourModel.clearTourProgress(),viewTourModel.clickedStartTour()):
ZAP.showConfirmation({promptHTML:"You viewed this lesson <var>"+g+"</var>. Would you like to resume from where you left off, or start over?",confirmText:"Resume",cancelText:"Start Over",confirmAction:function(){viewTourModel.restoreTourProgress()},cancelAction:function(){viewTourModel.clearTourProgress()},bottomBarText:viewTourModel.viewerName()?f:void 0},{changeName:function(){$("#identifyViewerPrompt").reveal()}})}if(b)if(HTMLYouTubeVideoElement._preloadYouTubeAPI(),viewTourModel.tour().filterBypass())ZAP.Reachability.YouTubeProxy=
!0;else ZAP.on("reachability:detected",function(){if(!ZAP.Reachability.YouTube){zp.pause();var a=$("#filterWarning");d&&"student"!==d.orgPosition&&viewTourModel.tour().owner()===d._id&&a.find("a").text("Fix This").attr({href:"/settings#filter",target:""});a.addClass("triggered")}});window.addEventListener("offline",function(){zp.pause();var a=ZAP.forceAlert("You are currently offline. Please reconnect to the internet to continue viewing."),b=function(){a();window.removeEventListener("online",b)};
window.addEventListener("online",b)});forwardEscapesToParent()})};
ZAP.runTourSignupPage=function(){$(document).ready(function(){window.defineSignupViewModel();var b=new window.SignupViewModel;window.addKnockoutBindings(ko);b.tour=ko.observable(new ZAP.Tour(window.initialTour,{preSynced:!0,temporary:!0}));ko.applyBindings(b);$("#authenticate").reveal({closeOnBackgroundClick:!1,disableEsc:!0,opened:function(){var b=$(window).height(),a=$("#authenticate").outerHeight();a<b&&$("#authenticate").css("top",(b-a)/2+"px")}});window.authComplete=function(g,a){g&&b.showModalError(g);
a&&(window.location=a)};window!==top&&$(".service-btn").attr("target","_blank");forwardEscapesToParent()})};
ZAP.runViewTouriPhonePage=function(){amplify.store("hasApp")?(window.location=window.iosURL,$(document).ready(function(){$(".iphone-tour-buttons").show()})):$(document).ready(function(){$(".iphone-ask-installed").show();$("#noBtn").on("click",function(){window.location="https://itunes.apple.com/us/app/zaption-interact-learn-video/id925786228?mt=8&uo=4"});$("#yesBtn").on("click",function(){$(".iphone-ask-installed").hide();$(".iphone-tour-buttons").show();amplify.store("hasApp",!0);window.location=
window.iosURL})})};
var defineExploreViewModel=function(){ZAP.defineAmplifyRequests("search explore browseItems collectionItems createCollection deleteCollection deleteItem undeleteItem createTour".split(" "));var b=function(a,b,e){a._afterSync(function(a){a&&(navigator.onLine?ZAP.showAlert(b+": "+a):ZAP.showAlert(b+" because you are not connected to the internet. Please reconnect to the internet and try again."));e&&amplify.request.invalidate(e)})},g={dragging:{type:Boolean,sync:"none"},temporary:{type:Boolean,sync:"none"},
displayType:{compute:function(){var a=this;if("Tour"===a._instanceType)return!0===a.published()?"Published":"Draft";if("TourListing"===a._instanceType)return"Listing";if("Finished"===a.encodeStatus())switch(a.videoType()){case "YouTube":return"YouTube";case "Vimeo":return"Vimeo";case "S3":return"Zaption";case "MP4URL":return"External";case "MediaCore":return"MediaCore";default:if(window.privateVideoArchives){var b=_.find(window.privateVideoArchives,function(b){return b.videoType===a.videoType()});
if(b)return b.videoDisplayType}return"Unknown"}else return"Failed"===a.encodeStatus()?"Failed":"Processing"},sync:"none"},displayClass:{compute:function(){switch(this.displayType()){case "Draft":return"draft-item";case "Processing":return"encoding-item";case "Failed":return"failed-item";default:return""}},sync:"none"},hidden:{type:Boolean,sync:"none"}};$.extend(ZAP.Video.schema,g);$.extend(ZAP.Tour.schema,g);ZAP.Video.methods.clickEvent=function(){var a=this;a.deleted()?ZAP.showAlert('This item is deleted. To access it you must undelete it from the context menu or drag it to the "All" filter.'):
"Processing"===a.displayType()?(a.checkIfTranscoding(),ZAP.showAlert("You cannot view this video until it is finished processing.")):"Failed"===a.displayType()?(amplify.request({resourceId:"deleteItem",data:{itemType:"video",id:a._id},success:function(){a.deleted(!0);amplify.request.invalidate(["browseItems","collectionItems"])},error:function(){amplify.request.invalidate(["browseItems","collectionItems"])}}),ZAP.showAlert("This video failed to encode and will be removed now. Please try to upload this video again.")):
window.location.href="/videos/"+a._id};ZAP.Tour.methods.clickEvent=function(){this.deleted()?ZAP.showAlert('This item is deleted. To access it you must undelete it from the context menu or drag it to "All" filter.'):this.published()?window.location.href="/lessons/"+this._id:window.location.href="/lessons/"+this._id+"/edit"};ZAP.Collection.methods.addItem=function(a){this.items.push(a._id);b(this,"Error adding item to collection",["collectionItems"])};ZAP.Collection.methods.removeItem=function(a){this.items.remove(a._id);
b(this,"Error removing item from collection",["collectionItems"])};window.ExploreViewModel=function(){var a=this,b={success:function(b){a.items.removeAll();a.numPages(b.totalCount/a.resultsPerPage());b=b.results;var f;switch(a.currentItemType()){case "video":for(f=0;f<b.length;f++)a.items.push(new ZAP.Video(b[f],{preSynced:!0}));break;case "tour":for(f=0;f<b.length;f++)a.items.push(new ZAP.Tour(b[f],{preSynced:!0}));break;default:ZAP.showAlert("Current item type unknown")}a.refreshBrowseResults.resolveRequest()},
error:function(b,f){a.refreshBrowseResults.resolveRequest();"abort"!==f&&ZAP.showAlert(b.message)}};a.sortType=ko.observable("dateUpdatedDesc");a.workingSearchTerm=ko.observable("");a.searchTerm=ko.observable("");a.collId=ko.observable("");a.currentSection=ko.observable("");a.currentSub=ko.observable();a.updateMessage=ko.observable("");a.currentItemType=ko.observable("");a.currentDisplayItemType=ko.computed(function(){switch(a.currentItemType()){case "tour":return"lesson";case "video":return"video";
default:return"item"}});a.resultsPerPage=ko.computed(function(){return"tour"===a.currentItemType()?15:"video"===a.currentItemType()&&window.VideoUploader.enabledUploadOptions.length?15:16});a.items=ko.observableArray();a.numPages=ko.observable(1);a.gridView=ko.observable(!0);a.currentPage=ko.observable(0);a.maxPages=ko.observable(9);a.paginationStart=ko.computed(function(){var b=a.currentPage(),f=a.maxPages(),d=(f-1)/2,e=a.numPages();return 0>b-d?0:e-d<=b?e-f:b-d});a.paginationEnd=ko.computed(function(){var b=
a.currentPage(),f=a.maxPages(),d=(f-1)/2,e=a.numPages();return 0>b-d?f:e-d<b?e:b+d+1});a.resetQuery=function(){a.collId("");a.currentPage(0);a.searchTerm("")};var e=function(){a.currentPage(0);a.refreshBrowseResults()};Sammy(function(){var b=function(b,c){return function(){a.currentItemType(b);a.sortType()||a.sortType("dateUpdatedDesc");c&&(a.currentSection(""),a.resetQuery())}};this.get("/lessons",b("tour",!0));this.get("/lessons#",b("tour"));this.get("/videos",b("video",!0));this.get("/videos#",
b("video"));b=function(){location.hash=""};this.get("/lessons#_=_",b);this.get("/videos#_=_",b);this.get("/lessons#:section",function(b,c){a.currentItemType("tour");a.currentSection("all"===this.params.section?"":this.params.section);a.sortType()||a.sortType("dateUpdatedDesc");c()});this.get("/videos#:section",function(b,c){a.currentItemType("video");a.currentSection("all"===this.params.section?"":this.params.section);a.sortType()||a.sortType("dateUpdatedDesc");c()});this.after(function(){var b=this;
ko.tasks.processImmediate(function(){var c=b.params.query;!c&&a.searchTerm()?a.resetQuery():a.searchTerm(c||"")});var c=b.params.collId;c?a.collId(c):a.collId("");(c=parseInt(b.params.page,10))?a.currentPage(c-1):a.currentPage(0);(c=b.params.sort)?a.sortType(c):a.sortType("dateUpdatedDesc");"list"===b.params.view&&a.gridView(!1)});this.notFound=function(){return!0};this._checkFormSubmission=function(a){if("searchForm"===a.id)return!1}}).run();$.extend(ZAP.Collection.schema,{editing:{type:Boolean,
"default":!1,sync:"none"}});a.collections=ko.observableArray(window.initialCollections.map(function(a){return new ZAP.Collection(a,{preSynced:!0})}));a.selectedCollection=ko.computed(function(){if(a.collId()){var b=_.find(a.collections(),function(b){return b._id===a.collId()});b||a.collId(!1);return b}});a.header={title:ko.computed(function(){switch(a.currentItemType()){case "tour":return"My Lessons";case "video":return"My Videos";default:return""}}),subTitle:ko.computed(function(){switch(a.currentItemType()){case "tour":return"View, edit and organize your lessons";
case "video":return"View, upload, and organize your videos";default:return""}})};a.searchItems=function(b){a.searchTerm($(b).find("input[type=text]").val())};a.removeItemFromCurrentCollection=function(b,f){a.items.remove(b);var d=a.selectedCollection();d&&(d.removeItem(b),f&&a.updateMessage('"'+(b.name()||"Untitled Lesson")+'" was removed from "'+d.name()+'"!'))};a.undeleteItem=function(b){a.items.remove(b);b.deleted(!1);amplify.request({resourceId:"undeleteItem",data:{itemType:a.currentItemType(),
id:b._id},success:function(){a.updateMessage('"'+(b.name()||"Untitled Lesson")+'" was undeleted!');amplify.request.invalidate(["browseItems","collectionItems"])},error:function(a){amplify.request.invalidate(["browseItems","collectionItems"]);ZAP.showAlert("Failed to undelete item "+b.name()+" due to error: "+a.message)}})};a.deleteItem=function(b){b.currentUserHasWritePermissions()?(a.items.remove(b),b.deleted(!0),amplify.request({resourceId:"deleteItem",data:{itemType:a.currentItemType(),id:b._id},
success:function(){a.updateMessage('"'+(b.name()||"Untitled Lesson")+'" was deleted!');amplify.request.invalidate(["browseItems","collectionItems"])},error:function(a){amplify.request.invalidate(["browseItems","collectionItems"]);ZAP.showAlert("Failed to delete item "+b.name()+" due to error: "+a.message)}})):a.updateMessage("You don't have permission to delete \""+(b.name()||"Untitled Lesson")+'"!')};a.addOrMoveToCollection=function(b){var f="added";"collection"===a.currentSection()&&(a.removeItemFromCurrentCollection(b),
f="moved");this.addItem(b);a.updateMessage('"'+(b.name()||"Untitled Lesson")+'" was '+f+' to "'+this.name()+'"!')};a.addCollection=function(){amplify.request({resourceId:"createCollection",data:{itemType:a.currentItemType()},success:function(b){b=new ZAP.Collection(b,{preSynced:!0});a.collections.unshift(b);a.editCollection(b)},error:function(a){ZAP.showAlert(a.message)}})};a.editCollection=function(a){a.editing(!0)};a.removeCollection=function(b){amplify.request({resourceId:"deleteCollection",data:{itemType:a.currentItemType(),
id:b._id},success:function(){a.collections.remove(b);a.collId()===b._id&&a.collId("")},error:function(a){ZAP.showAlert(a.message)}})};a.selectCollection=function(b){a.collId(b._id)};a.startDraggingItem=function(a){a.dragging(!0)};a.stopDraggingItem=function(a){a.dragging(!1)};a.createTourWithVideo=function(a){"Processing"===a.displayType()?ZAP.showAlert("You cannot add this video until it is finished processing."):"Failed"===a.displayType()?(amplify.request({resourceId:"deleteItem",data:{itemType:"video",
id:a._id},success:function(){a.deleted(!0);amplify.request.invalidate(["browseItems","collectionItems"])},error:function(){amplify.request.invalidate(["browseItems","collectionItems"])}}),ZAP.showAlert("This video failed to encode and will be removed now. Please try to upload this video again.")):amplify.request({resourceId:"createTour",data:{newTour:{video:a.toJSON()}},success:function(a){window.location.href="/lessons/"+a._id+"/edit"},error:function(a){log(a)}})};a.currentItemTypeTitle=ko.computed(function(){return(a.currentItemType()||
"item").toSentenceCase()});a.currentSearchPrompt=ko.computed(function(){switch(a.currentItemType()){case "video":return"Search your videos";case "tour":return"Search your lessons";default:return"Search items"}});a.pageTitle=ko.computed(function(){if(a.collId())return a.selectedCollection().name()+" - Zaption";if(a.currentItemType()){if("tour"===a.currentItemType())return"My Lessons - Zaption";if("video"===a.currentItemType())return"My Videos - Zaption"}else return"My Items - Zaption"});a.nextPage=
function(){a.numPages()-1>a.currentPage()&&a.currentPage(a.currentPage()+1)};a.prevPage=function(){0<a.currentPage()&&a.currentPage(a.currentPage()-1)};var k=function(){var a=window.location.hash.split("?");return 2>a.length?{}:ZAP.util.getParams(a[1])},f=function(b){var f=window.location;b=$.param(b);var d=f.protocol+"//"+f.host+f.pathname+"#",d=d+a.currentSection();b&&(d+="?"+b);f.href!==d&&(f.href=d)};a.currentPage.subscribe(function(a){var b=k();b.page=a+1;f(b)});a.gridView.subscribe(function(a){var b=
k();b.view=a?"grid":"list";f(b)});a.refreshBrowseResults=function(){if(a.refreshBrowseResults.pendingRequest)a.refreshBrowseResults.requestAgain=!0,a.refreshBrowseResults.pendingRequest.abort();else{ko.tasks.processImmediate(function(){a.refreshBrowseResults.requestIsPending(!0)});var c,f={sort:a.sortType(),numItems:a.resultsPerPage(),page:a.currentPage(),collId:a.collId(),itemType:a.currentItemType()};a.searchTerm()||(f.typeFilter=a.currentSection());a.collId()?c="collectionItems":(c="browseItems",
f.itemType=a.currentItemType());a.searchTerm()&&("explore"===c?(f.gallerySection="search",f.query=a.searchTerm()):f.terms=a.searchTerm());c=_.extend({resourceId:c,data:f},b);a.refreshBrowseResults.pendingRequest=amplify.request(c)}};a.refreshBrowseResults.requestIsPending=ko.observable(!0);a.refreshBrowseResults.resolveRequest=function(){a.refreshBrowseResults.pendingRequest=null;ko.tasks.processImmediate(function(){a.refreshBrowseResults.requestIsPending(!1)});a.refreshBrowseResults.requestAgain&&
(a.refreshBrowseResults.requestAgain=!1,a.refreshBrowseResults())};a.currentPage.subscribe(function(){a.refreshBrowseResults()});a.searchTerm.subscribe(function(){var b=a.searchTerm();a.workingSearchTerm(b);var d=k();b?("search"===a.currentSection()?e():a.currentSection("search"),d.query=b):("search"===a.currentSection()&&a.currentSection(""),delete d.query);f(d)});a.collId.subscribe(function(){var b=k();a.collId()?(a.currentSection("collection"),a.searchTerm(""),e(),b.collId=a.collId(),b.page=1):
(delete b.collId,delete b.page,"collection"===a.currentSection()&&a.currentSection(""));f(b)});a.sortType.subscribe(function(a){var b=k();a!==b.sort&&(b.sort=a,f(b),e())});a.currentSection.subscribe(function(){var b=k();b.view||a.gridView()||(b.view="list",f(b));"collection"!==a.currentSection()&&("search"!==a.currentSection()&&a.searchTerm(""),a.collId()&&a.collId(""),e())});a.currentItemType.subscribe(function(a){"video"===a?($("#toursNavMenu").removeClass("selected"),$("#videosNavMenu").addClass("selected")):
($("#toursNavMenu").addClass("selected"),$("#videosNavMenu").removeClass("selected"));e()});a.tour=ko.observable();a.showTourSharingModal=function(b){b&&"Tour"===b._instanceType&&(a.tour(b),a.shareModalVM||(a.shareModalVM=new window.ShareTourViewModel(a.tour),a.shareModalVM.bind()),a.shareModalVM.show())};a.showTourUnpublishWarning=function(b){b&&"Tour"===b._instanceType&&(a.tour(b),ko.processAllDeferredBindingUpdates(),$("#unpublishTourWarning").reveal(),amplify.request.invalidate(["browseItems",
"collectionItems"]))};a.cloneTour=function(a){a=$('<form method="post" action="/tours/'+a._id+'/clone"></form>');a.append('<input type="hidden" name="_csrf" value="'+window.csrfToken+'">');$("body").append(a);a.submit()};a.createPresentation=function(a){ZAP.presenter.continueOrCreatePresentation(a);return!1};a.refreshBrowseResults()}};
ZAP.runExplorePage=function(){defineExploreViewModel();$(document).ready(function(){var b=new window.ExploreViewModel;window.addKnockoutBindings(ko);$(".application-container").fadeTo(300,1);ko.applyBindings(b,$("html")[0]);if($("#refer").length){var g=$("#refer");window.defineReferralsViewModel();var a=new window.ReferralModalViewModel;ko.applyBindingsToDescendants(a,g[0]);g.reveal()}var d;$(document).on("vclick",".uploadVideo",function(){if(window.videoUploader&&!d){var a=window.videoUploader;d=
!0;a.on("tempvideoavailable",function(a){"video"===b.currentItemType()&&(b.items.pop(),b.items.unshift(a))});a.on("finalvideoavailable",function(a,f){"video"===b.currentItemType()&&(b.items.remove(f),b.items.unshift(a),amplify.request.invalidate("browseItems"))});a.on("uploadfailed",function(a){"video"===b.currentItemType()&&b.items.remove(a)})}})})};
var defineLTIExploreViewModel=function(){ZAP.defineAmplifyRequests(["browseItems","collectionItems","attachToLTI"]);$.extend(ZAP.Tour.schema,{displayType:{compute:function(){return!0===this.published()?"Published":"Draft"},sync:"none"},displayClass:{compute:function(){switch(this.displayType()){case "Draft":return"draft-item";default:return""}},sync:"none"}});ZAP.Tour.methods.clickEvent=function(){var b=this;amplify.request({resourceId:"attachToLTI",data:{id:b._id,ltiSessionId:window.ltiSessionId},
success:function(){window.location.replace("/lessons/"+b._id+"/lti/embed?ltiSessionId="+encodeURIComponent(window.ltiSessionId))},error:function(b){ZAP.showAlert(b.message)}})};window.LTIExploreViewModel=function(){var b=this,g={success:function(a){b.items.removeAll();b.numPages(a.totalCount/b.resultsPerPage());a=a.results;var e;switch(b.currentItemType()){case "tour":for(e=0;e<a.length;e++)b.items.push(new ZAP.Tour(a[e],{preSynced:!0}));break;default:ZAP.showAlert("Current item type unknown")}b.refreshBrowseResults.resolveRequest()},
error:function(a,e){b.refreshBrowseResults.resolveRequest();"abort"!==e&&ZAP.showAlert(a.message)}};b.sortType=ko.observable("dateUpdatedDesc");b.workingSearchTerm=ko.observable("");b.searchTerm=ko.observable("");b.collId=ko.observable("");b.currentSection=ko.observable("");b.currentItemType=ko.observable("tour");b.items=ko.observableArray();b.resultsPerPage=ko.observable(12);b.numPages=ko.observable(1);b.currentPage=ko.observable(0);b.maxPages=ko.observable(9);b.paginationStart=ko.computed(function(){var a=
b.currentPage(),e=b.maxPages(),g=(e-1)/2,f=b.numPages();return 0>a-g?0:f-g<=a?f-e:a-g});b.paginationEnd=ko.computed(function(){var a=b.currentPage(),e=b.maxPages(),g=(e-1)/2,f=b.numPages();return 0>a-g?e:f-g<a?f:a+g+1});b.collections=ko.observableArray(window.initialCollections.map(function(a){return new ZAP.Collection(a,{preSynced:!0})}));b.selectedCollection=ko.computed(function(){if(b.collId()){var a=_.find(b.collections(),function(a){return a._id===b.collId()});a||b.collId(!1);return a}});b.searchItems=
function(a){b.searchTerm($(a).find("input[type=text]").val())};b.selectCollection=function(a){b.collId(a._id)};b.nextPage=function(){b.numPages()-1>b.currentPage()&&b.currentPage(b.currentPage()+1)};b.prevPage=function(){0<b.currentPage()&&b.currentPage(b.currentPage()-1)};b.refreshBrowseResults=function(){if(b.refreshBrowseResults.pendingRequest)b.refreshBrowseResults.requestAgain=!0,b.refreshBrowseResults.pendingRequest.abort();else{ko.tasks.processImmediate(function(){b.refreshBrowseResults.requestIsPending(!0)});
var a,e={sort:b.sortType(),numItems:b.resultsPerPage(),page:b.currentPage(),collId:b.collId(),itemType:b.currentItemType()};b.searchTerm()||(e.typeFilter=b.currentSection()||"editablePublished");b.collId()?(e.typeFilter="editablePublished",a="collectionItems"):(a="browseItems",e.itemType=b.currentItemType());b.searchTerm()&&(e.terms=b.searchTerm(),e.typeFilter="editablePublished");a=_.extend({resourceId:a,data:e},g);b.refreshBrowseResults.pendingRequest=amplify.request(a)}};b.refreshBrowseResults.requestIsPending=
ko.observable(!0);b.refreshBrowseResults.resolveRequest=function(){b.refreshBrowseResults.pendingRequest=null;ko.tasks.processImmediate(function(){b.refreshBrowseResults.requestIsPending(!1)});b.refreshBrowseResults.requestAgain&&(b.refreshBrowseResults.requestAgain=!1,b.refreshBrowseResults())};b.resetQuery=function(){b.collId("");b.currentPage(0);b.searchTerm("")};var a=function(){b.currentPage(0);b.refreshBrowseResults()};b.currentPage.subscribe(function(){b.refreshBrowseResults()});b.searchTerm.subscribe(function(){var d=
b.searchTerm();b.workingSearchTerm(d);d?"search"===b.currentSection()?a():b.currentSection("search"):"search"===b.currentSection()&&b.currentSection("")});b.collId.subscribe(function(){b.collId()?(b.currentSection("collection"),b.searchTerm(""),a()):"collection"===b.currentSection()&&b.currentSection("")});b.sortType.subscribe(function(){a()});b.currentSection.subscribe(function(){"collection"!==b.currentSection()&&("search"!==b.currentSection()&&b.searchTerm(""),b.collId()&&b.collId(""),a())});b.refreshBrowseResults()}};
ZAP.runLTIExplorePage=function(){defineLTIExploreViewModel();$(document).ready(function(){var b=new window.LTIExploreViewModel;window.addKnockoutBindings(ko);$(".application-container").fadeTo(300,1);ko.applyBindings(b)})};
var defineLTIBrowseViewModel=function(){amplify.request.define("browseItems","ajax",{url:"/ajax/tours",dataType:"json",type:"GET",decoder:"zsend",cache:6E4});amplify.request.define("collectionItems","ajax",{url:"/ajax/tours/collections/{collId}",dataType:"json",type:"GET",decoder:"zsend",cache:6E4});window.LTIBrowseViewModel=function(){var b=this;b.currentPage=ko.observable(0);b.resultsPerPage=ko.observable(9);b.numPages=ko.observable(0);b.searchTerm=ko.observable("");b.pageTitle=ko.observable("Browse Lessons - Zaption");
b.showReset=ko.observable(!1);b.dataLoaded=ko.observable(!1);b.collection=ko.observable(null);b.items=ko.observableArray();var g=function(a){b.items.removeAll();_.forEach(a,function(a){b.items.push(new ZAP.Tour(a,{preSynced:!0,temporary:!0}))});b.dataLoaded(!0)};b.search=function(a){b.searchTerm(encodeURIComponent(a.searchText.value));0<b.currentPage()?b.currentPage(0):e()};b.resetTours=function(){b.collection()?b.collection(null):b.searchTerm()&&(b.searchTerm(""),$("input[name=searchText]").val(""));
0<b.currentPage()?b.currentPage(0):e();b.showReset(!1)};b.tourClick=function(a){window.location=window.ltiReturnURL+"?return_type=lti_launch_url&url="+encodeURIComponent("https://www.zaption.com/basic_lti?lti_tour="+a._id)+"&title=Take+this+interactive+video+lesson&text=Zaption+Lesson:+"+encodeURIComponent(a.name()||"Untitled Lesson")};var a=function(a){void 0!==a.totalCount&&b.numPages(a.totalCount/b.resultsPerPage());g(a.results)},d=function(a,f){"abort"!==f&&ZAP.showAlert(a.message);b.dataLoaded(!0)},
e=b.refreshResults=function(){var e="browseItems",f={sort:"dateUpdatedDesc",numItems:b.resultsPerPage(),page:b.currentPage(),typeFilter:"published",filter:"All",itemType:"tour"};b.pageTitle("Browse Lessons - Zaption");b.collection()&&b.collection()._id?(f.collId=b.collection()._id,e="collectionItems",b.pageTitle(b.collection().name()+" - Zaption"),b.showReset(!0)):b.searchTerm()?(b.pageTitle("Search Results - Zaption"),f.terms=b.searchTerm(),b.showReset(!0)):b.searchTerm()||b.showReset(!1);b.dataLoaded(!1);
amplify.request({resourceId:e,success:a,error:d,data:f})};b.nextPage=function(){b.numPages()-1>b.currentPage()&&b.currentPage(b.currentPage()+1)};b.prevPage=function(){0<b.currentPage()&&b.currentPage(b.currentPage()-1)};b.currentPage.subscribe(e)}};ZAP.runLTIBrowsePage=function(){defineLTIBrowseViewModel();$(document).ready(function(){var b=new window.LTIBrowseViewModel;ko.applyBindings(b,$("html")[0]);window.addKnockoutBindings(ko);b.refreshResults();$(".application-container").show()})};
(function(){ZAP.editor={};ZAP.editor.timeToPixels=function(b,g,a,d){if(0===g)return 0;b=b/g*a;d&&b--;return b};ZAP.editor.pixelsToTime=function(b,g,a,d){d&&b++;return b/a*g};ZAP.editor.updateOverlaps=function(b){b=b.children(".timeline-element");for(var g=0;g<b.length;g++){var a=b.eq(g),d=parseFloat(a.css("left"),10);if(a.hasClass("has-marker")){var e=0;a.siblings(".timeline-element").each(function(a,b){var c=parseFloat($(b).css("left"),10);c>d||$(b).hasClass("has-marker")&&c+4>=d&&e++});a.children(".marker").css("top",
"");a.children(".marker").css("top","-="+e+"px")}}};ZAP.editor.setPositionAndSpace=function(b,g,a){var d="function"===typeof a.zp?a.zp():a.zp,e=b.elementType(),k=d.currentTime(),d=d.getDuration();b.clip(a.activeClip()._id);b.space(g);var f=b.outTime()-b.inTime();"Replay"===e?(b.outTime(k),b.inTime(Math.max(0,k-f))):(b.inTime(k),b.outTime(Math.min(k+f,d)));b.children().length&&b.children().forEach(function(b){ZAP.editor.setPositionAndSpace(b,g,a)});return b};ZAP.editor.fixElement=function(b){b._id=
(new ZAP.ObjectId).toString();b.dateCreated=Date.now();(b.choices||[]).forEach(function(a){a.__oldId=a._id;a._id=(new ZAP.ObjectId).toString()});var g=[];(b.actions||[]).forEach(function(a){a._id=(new ZAP.ObjectId).toString();var d=a.jumpType&&a.jumpTarget;if(a.feedbackType||a.feedbackText||d)if(a.criteria&&a.criteria.choice){if(d=_.find(b.choices||[],function(b){return b.__oldId===a.criteria.choice}))a.criteria.choice=d._id,g.push(a)}else g.push(a)});b.actions=g;(b.children||[]).forEach(ZAP.editor.fixElement)};
ZAP.editor.getOpenTimesInClip=function(b,g,a,d){var e=_.find(g.tour().clips(),function(a){return a._id===b});if(!e)return[];g=e.elements().filter(function(b){return b.space()===a});for(var e=[{start:0,end:e.duration()}],k=0;k<g.length;k++){var f=g[k],c=f.inTime(),l=f.effectiveOutTime();"Stop"===f.behavior()&&(l=c);if(!d||f._id!==d._id){for(var h,f=0;f<e.length;f++){var q=e[f];if(q.start<=c&&q.end>=l){h=q;break}}h&&(e.splice(f,1),h.start<c&&e.push({start:h.start,end:c}),h.end>l&&e.push({start:l,end:h.end}))}}e.sort(function(a,
b){return a.start===b.start?a.end-b.end:a.start-b.start});return e};ZAP.editor.checkElementPlacement=function(b,g){var a=b.space();if(0.01>b.duration())return!1;var d;"MainBox"===a?d=g.currentVideoScreenElements():"Sidebar"===a&&(d=g.currentSidebarElements());if(!d)return!0;for(a=0;a<d.length;a++)if(ZAP.editor.elementsIntersect(b,d[a]))return!1;return!0};ZAP.editor.elementsIntersect=function(b,g){return!!(b.inTime()<=g.effectiveOutTime()&&b.effectiveOutTime()>=g.inTime()||g.inTime()<=b.effectiveOutTime()&&
g.effectiveOutTime()>=b.inTime())};ZAP.editor.placeElementInClip=function(b,g,a){if(ZAP.editor.checkElementPlacement(b,g))return b;var d=b.space(),e=b.inTime(),k=b.effectiveOutTime(),f=b.duration(),c=Math.min(f,3);g=ZAP.editor.getOpenTimesInClip(b.clip(),g,d,b);d=(b.inTime()+b.effectiveOutTime())/2;a&&(d=b.inTime());a=ZAP.editor.nextOpenInterval(d,c,g);c=ZAP.editor.prevOpenInterval(d,c,g);if(!a&&!c)return null;a&&(!c||Math.abs(a.start-e)<=Math.abs(k-c.end))?"Replay"===b.elementType()?(b.outTime(Math.min(k,
a.end)),b.inTime(Math.max(b.effectiveOutTime()-f,a.start))):(b.inTime(Math.max(e,a.start)),b.outTime(Math.min(b.inTime()+f,a.end))):(b.outTime(Math.min(k,c.end)),b.inTime(Math.max(b.effectiveOutTime()-f,c.start)));return b};ZAP.editor.nextOpenInterval=function(b,g,a){if(a){for(var d,e=0;e<a.length;e++)if(d=a[e],!(d.end<b)&&d.end-d.start>g)return d;return null}};ZAP.editor.prevOpenInterval=function(b,g,a){if(a){for(var d=null,e=0;e<a.length;e++){var k=a[e];if(k.start>b)break;k.end-k.start>g&&(d=k)}return d}}})();
(function(){var b;ZAP.Tour.loadExtensions("sidebarElements","videoScreenElements");var g=function(){var a=this;a.tour=ko.observable(new ZAP.Tour(window.initialTour,{preSynced:!0}));a.liveMainElements=ko.observable(!1);a.liveSideElements=ko.observable(!1);a.activeClip=ko.observable(!1);a.viewerName=ko.observable(window.currentUser.name);a.presentationEnded=ko.observable(!1);a.currentPlaylist=ko.computed(function(){return a.tour().clips()});a.zp=ko.observable();a.tour().elementsFilter(function(a){var b=
"DrawnResponse"===a.elementType();a=a.presentationId()&&a.presentationId()!==window.initialPresentation._id;return!b&&!a});a.currentSidebarElements=ko.computed(function(){var b=a.activeClip();if(!b)return[];for(var b=b._id,c=a.tour().sidebarElements(),d=[],e=0;e<c.length;e++)c[e].clip()===b&&d.push(c[e]);return d});a.mainActiveElement=ko.computed(function(){return a.liveMainElements()&&a.liveMainElements().activeElement()});a.sideActiveElement=ko.computed(function(){return a.liveSideElements()&&a.liveSideElements().activeElement()});
a.activeDiscussion=ko.computed(function(){return a.sideActiveElement()&&"Discussion"===a.sideActiveElement().elementType()});a.currentVideoScreenElements=ko.computed(function(){var b=a.activeClip();if(!b)return[];for(var b=b._id,c=a.tour().videoScreenElements(),d=[],e=0;e<c.length;e++)c[e].clip()===b&&d.push(c[e]);return d});a.presentation=window.initialPresentation;a.attendees=ko.observableArray(a.presentation.activeUsers||[]);a.allAttendees=ko.observableArray(a.presentation.allUsers||[]);a.allAttendeeNames=
ko.computed(function(){var b=a.allAttendees();_.each(a.allAttendees(),function(b){b.hasOwnProperty("online")||_.extend(b,{online:ko.observable()});var f=_.some(a.attendees(),{identifier:b.identifier});b.online(f)});return _(b).chain().sortBy(function(a){return a.name.toLowerCase()}).reverse().sortBy(function(a){return a.online()}).reverse().value()});a.isAnswerVisible=ko.observable(!1);a.areResponsesVisible=ko.observable(!1);a.isQuickQuestionVisible=ko.observable(!1);a.isMarkerVisible=ko.observable(!1);
a.isPointerVisible=ko.observable(!1);a.areRaisedHandsVisible=ko.observable(!1);a.isJoinCodeVisible=ko.observable(!1);a.enableHands=ko.observable(a.presentation.enableHands);a.isAttendeeListVisible=ko.observable(!0);window.initialComments=window.initialComments?window.initialComments:[];a.raisedHands=ko.observableArray(window.initialComments);a.commentNotification=ko.observable(!1);a.sidebarMinimized=ko.observable(!0);a.isUserActive=ko.observable(!1);a.showFullScreenCloseButton=ko.observable(!1);a.isFullScreen=
ko.computed(function(){return a.zp()&&a.zp().isFullScreenMode()});a.isFullScreen.subscribe(function(b){!b&&a.zp()&&a.zp().pause()});a.onQuestionAdded=function(){a.isQuickQuestionVisible(!1)};a.isMainElementVisible=ko.computed(function(){return a.isFullScreen()&&a.mainActiveElement()&&!a.isQuickQuestionVisible()&&!a.areRaisedHandsVisible()});a.areMainElementControlsVisible=ko.computed(function(){return a.isMainElementVisible()&&(!a.sideActiveElement()||a.sidebarMinimized())&&(a.mainActiveElement().isResponseElement()||
"Group"===a.mainActiveElement().elementType()&&a.mainActiveElement().activeChild().isResponseElement())});a.isSideElementVisible=ko.computed(function(){return a.isFullScreen()&&a.sideActiveElement()&&!a.isQuickQuestionVisible()&&!a.areRaisedHandsVisible()});a.areSideElementControlsVisible=ko.computed(function(){return a.isSideElementVisible()&&!a.sidebarMinimized()&&(a.sideActiveElement().isResponseElement()||"Group"===a.sideActiveElement().elementType()&&a.sideActiveElement().activeChild().isResponseElement())});
a.areControlsVisible=ko.computed(function(){return a.isFullScreen()&&(a.isUserActive()||a.isMainElementVisible()||a.isSideElementVisible()||a.areRaisedHandsVisible())});a.areToolsVisible=ko.computed(function(){var b=a.areRaisedHandsVisible()||a.isQuickQuestionVisible()||a.isMarkerVisible();return a.isFullScreen()&&(a.isUserActive()||b)&&!a.isAttendeeListVisible()});a.toggleAttendeeList=function(){a.isAttendeeListVisible(!a.isAttendeeListVisible())};a.toggleAnswer=function(){a.isAnswerVisible(!a.isAnswerVisible())};
a.toggleResponses=function(){a.areResponsesVisible(!a.areResponsesVisible())};a.toggleQuickQuestion=function(){a.isQuickQuestionVisible(!a.isQuickQuestionVisible());a.isQuickQuestionVisible()&&(a.zp().pause(),a.areRaisedHandsVisible(!1),a.isMarkerVisible(!1),a.togglePointerCursor(!1),a.isJoinCodeVisible(!1))};a.toggleRaisedHands=function(){a.areRaisedHandsVisible(!a.areRaisedHandsVisible());a.areRaisedHandsVisible()&&(ZAP.util.track("Presenter: Showed raised hands"),a.zp().pause(),a.isQuickQuestionVisible(!1),
a.isMarkerVisible(!1),a.togglePointerCursor(!1),a.isJoinCodeVisible(!1))};a.toggleMarker=function(){a.isMarkerVisible(!a.isMarkerVisible());a.isMarkerVisible()&&(ZAP.util.track("Presenter: Started marker"),a.zp().pause(),a.areRaisedHandsVisible(!1),a.isQuickQuestionVisible(!1),a.togglePointerCursor(!1),a.isJoinCodeVisible(!1))};a.togglePointerCursor=function(b){a.isPointerVisible(b);$("html").toggleClass("presentation-pointer",b)};a.togglePointer=function(){a.togglePointerCursor(!a.isPointerVisible());
a.isPointerVisible()&&(ZAP.util.track("Presenter: Started pointer"),a.areRaisedHandsVisible(!1),a.isQuickQuestionVisible(!1),a.isMarkerVisible(!1),a.isJoinCodeVisible(!1))};a.toggleJoinCode=function(){a.isJoinCodeVisible(!a.isJoinCodeVisible());a.isJoinCodeVisible()&&(a.zp().pause(),a.areRaisedHandsVisible(!1),a.isQuickQuestionVisible(!1),a.togglePointerCursor(!1),a.isMarkerVisible(!1),a.sidebarMinimized(!0))};a.toggleEnableHands=function(){a.enableHands(!a.enableHands());a.listeningChannel.toggleEnableHands(a.enableHands())};
a.toggleSidebar=function(){a.sidebarMinimized(!a.sidebarMinimized());a.sidebarMinimized()&&ZAP.util.track("Presenter: Teacher minimized sidebar")};a.startButtonText=ko.computed(function(){return a.zp()?a.zp().currentTimeOnTour()===a.tour().totalDuration()?"Restart presentation":0<a.zp().currentTimeOnTour()?"Resume presentation":"Start presentation":"Start presentation"});a.sidebarButtonClass=ko.computed(function(){return a.sideActiveElement()&&"Group"===a.sideActiveElement().elementType()?"-"+a.sideActiveElement().activeChild().elementType():
a.sideActiveElement()?"-"+a.sideActiveElement().elementType():""});a.controlsShouldBeTransparent=ko.computed(function(){var b=a.mainActiveElement()&&"transparent"!==a.mainActiveElement().backgroundColorCode(),c=a.isSideElementVisible()&&!a.sidebarMinimized();return b&&!c});a.onMainPresentationButtonClick=function(){a.zp().currentTimeOnTour()>=a.tour().totalDuration()&&(a.zp().restartPlaylist(),amplify.request({resourceId:"openPresentation",data:{presentationId:a.presentation._id}}));a.startPresentation()};
a.startPresentation=function(){a.isAttendeeListVisible(!1);$(".presenter-fake-fullscreen").removeClass("presenter-fake-fullscreen");a.zp().goFullScreenVideo();if(window.needsCookieSet())return window.postCookieSet=function(){window.needsCookieSet()?ZAP.showAlert("Your browser has cookies disabled. You need to enable cookies in order to use Zaption."):a.startPresentation()},!0;var b=ZaptionPlayer("ZaptionPlayer");b.resumeElementsQueues();b.channel.play();b.playUnlessBlocked()};a.finishTour=function(){a.clearTourProgress();
a.presentationEnded(!0)};a.replayTour=function(){ZaptionPlayer("ZaptionPlayer").restartPlaylist()};a.updateTourProgress=function(){var b=ZaptionPlayer("ZaptionPlayer"),c=b.currentTime(),d={dateViewed:Date.now()};b.liveMainElements.stoppingVideo()?d.element=b.liveMainElements.activeElement()._id:b.liveSideElements.stoppingVideo()?d.element=b.liveSideElements.activeElement()._id:(d.clipIndex=b.playlist().indexOf(b.getCurrentItem()),d.time=c);window.currentUser?d.uid=window.currentUser._id:d.viewerName=
a.viewerName();amplify.store("ZPPresentationProgress/"+a.presentation._id,d,{expires:26784E5});a.updateTourProgress.lastUpdate=c};a.updateTourProgress.lastUpdate=0;a.hasValidProgress=function(){var b=amplify.store("ZPPresentationProgress/"+a.presentation._id);if(!b)return!1;var c=!b.uid&&!window.currentUser&&b.viewerName===a.viewerName()||window.currentUser&&b.uid===window.currentUser._id,d=a.tour().dateUpdated().getTime()<=b.dateViewed,b=b.element||0!==b.clipIndex||0!==b.time;return c&&d&&b};a.restoreTourProgress=
function(){var b=ZaptionPlayer("ZaptionPlayer"),c=amplify.store("ZPPresentationProgress/"+a.presentation._id);a.hasValidProgress()&&(c.element?b.goToElement(c.element):(b.setCurrentItem(c.clipIndex),b.seek(c.time,!0)))};a.clearTourProgress=function(){amplify.store("ZPPresentationProgress/"+a.presentation._id,null)};a.showPlaybackRate=ko.observable(!0);a.playbackRate=ko.observable(1);a.showPlayHints=ko.computed(function(){return a.liveMainElements()&&a.liveSideElements()?_.any([a.liveMainElements(),
a.liveSideElements()],function(a){if(!a.stoppingVideo())return!1;a=a.activeElement();return _(["TextScreen","ImageScreen","Drawing"]).contains(a.elementType())||"Group"===a.elementType()&&a.activeChild()&&_(["TextScreen","ImageScreen","Drawing"]).contains(a.activeChild().elementType())?!0:!1}):!1});a.listeningChannel=new ZAP.PresentationChannel(a.presentation._id);a.listeningChannel.on("joined",function(b){a.attendees(_.reject(a.attendees(),function(a){return a.identifier===b.user.identifier}));a.attendees.push(b.user);
a.allAttendees(_.reject(a.allAttendees(),function(a){return a.identifier===b.user.identifier}));a.allAttendees.push(b.user)});a.listeningChannel.on("left",function(b){a.attendees(_.reject(a.attendees(),function(a){return a.identifier===b.user}))});var d=_.throttle(function(){b.zp().channel.sendTime(a.zp().currentTimeOnTour())},1E3);a.listeningChannel.on("askForTime",d);var e;a.listeningChannel.on("raiseHand",function(b){b.presentation=a.presentation._id;b.tour=a.tour()._id;amplify.request({resourceId:"recordHandRaise",
data:b,success:function(c){b._id=c._id;a.raisedHands.push(b)}});a.commentNotification(!0);clearTimeout(e);e=setTimeout(function(){a.commentNotification(!1)},2E3)});var g=function(a,b){var d=[],d=_.reject(a().presentationResponses(),function(a){return a.user&&a.user===b.resp.user||a.fingerprint===b.fingerprint&&a.name===b.resp.name});b.resp.fingerprint=b.fingerprint;d.push(b.resp);a().presentationResponses(d)};a.listeningChannel.on("responseReceived",function(b){a.mainActiveElement()&&(a.mainActiveElement()._id===
b.element&&g(a.mainActiveElement,b),"Group"===a.mainActiveElement().elementType()&&a.mainActiveElement().activeChild()._id===b.element&&g(a.mainActiveElement().activeChild,b));a.sideActiveElement()&&(a.sideActiveElement()._id===b.element&&g(a.sideActiveElement,b),"Group"===a.sideActiveElement().elementType()&&a.sideActiveElement().activeChild()._id===b.element&&g(a.sideActiveElement().activeChild,b))});ZAP.realtime.channel("remote-tour-"+a.tour()._id).subscribe("request-timestamp",function(){ZAP.realtime.channel("remote-tour-"+
a.tour()._id).publish("current-timestamp",a.zp().currentTimeOnTour().toString(),!0)})};ZAP.runPresentationPage=function(){ZAP.defineViewTourViewModels();$(document).ready(function(){window.addKnockoutBindings(ko);b=new g;ko.applyBindings(b);$("body").addClass("presenter-fake-fullscreen");b.showFullScreenCloseButton(!0);$(".close-presenter-fake-fullscreen").on("click",function(){b.zp().exitFullScreen()});window.zp=ZaptionPlayer("ZaptionPlayer");b.zp(window.zp);b.zp().channel.ready();window.onbeforeunload=
function(){var a=new ZAP.PresentationChannel(b.presentation._id,!0);if(b.presentationEnded())a.end();else{var d=b.zp().hasElementsRemaining(),c=0.95<b.zp().currentTimeOnTour()/b.tour().totalDuration();!d&&c?a.end():a.away()}};b.playheadMouseoverText=ko.computed(function(){return ZAP.util.secondsToTimestamp(b.zp().currentTimeOnTour())+" / "+ZAP.util.secondsToTimestamp(b.tour().totalDuration())});var a,d=[0,0],e=_.throttle(function(e){if(e.pageX!==d[0]||e.pageY!==d[1])d[0]=e.pageX,d[1]=e.pageY,clearTimeout(a),
b.isUserActive(!0),0===$(".presentation-buttons button:hover").length&&0===$("player-controls:hover").length&&(a=window.setTimeout(function(){b.isUserActive(!1)},1E3))},500);$("html").on("mousemove",e);b.liveMainElements(b.zp().liveMainElements);b.liveSideElements(b.zp().liveSideElements);b.zp().liveMainElements.activeElement.subscribe(b.updateTourProgress.bind(b));b.zp().liveSideElements.activeElement.subscribe(b.updateTourProgress.bind(b));b.zp().on("timeupdate",function(){1<b.zp().currentTime()&&
1.5<Math.abs(b.zp().currentTime()-b.updateTourProgress.lastUpdate)&&b.updateTourProgress()});b.zp().isFullScreenMode.subscribe(function(a){a||b.presentationEnded()||(b.zp().channel.pause(),b.togglePointerCursor(!1))});b.zp().on("ended",function(){b.finishTour()});b.zp().on("play",function(){b.isQuickQuestionVisible(!1);b.areRaisedHandsVisible(!1);b.isMarkerVisible(!1)});b.zp().on("switchedplaylistitem",function(){for(var a=b.zp().getCurrentItem()._id,d,c=b.tour().clips(),e=0;e<c.length;e++)if(c[e]._id===
a){d=c[e];break}d.transcript()&&!d.transcriptObject()&&d.loadTranscript();b.activeClip(d)});0<b.tour().clips().length&&b.activeClip(b.tour().clips()[0]);ZAP.realtime.channel("presenter-code-"+b.presentation.code).publish("presentationChanged",{action:"presentationChanged",presentationId:b.presentation._id});$(".application-container").show();e=amplify.store("ResumingPresentation/"+b.presentation._id);window.isiPhone||window.isTablet?(b.zp().exitFullScreen(),ZAP.showAlert("Sorry, but you can't present from a tablet yet. Please start your presentation from a laptop or desktop computer instead.<br><br>Your viewers can join from any device, including tablets or smartphones.",
{allowHTML:!0,afterClose:function(){window.location="/lessons"}})):b.hasValidProgress()&&!e?(e=moment(amplify.store("ZPPresentationProgress/"+b.presentation._id).dateViewed).fromNow(),ZAP.showConfirmation({promptHTML:"You started a presentation <var>"+e+"</var>. Would you like to resume, or start over?",confirmText:"Resume",cancelText:"Start Over",confirmAction:function(){b.restoreTourProgress();b.startPresentation()},cancelAction:function(){b.clearTourProgress();b.zp().channel.ready()}})):e&&(b.restoreTourProgress(),
amplify.store("ResumingPresentation/"+b.presentation._id,null));!$("#presenterWalkthrough").length||window.needsWelcome||ZAP.ui.pageIsFramed()||$("#refer").length||window.isiPhone||window.isTablet||$("#presenterWalkthrough").fadeIn()})}})();
